version: '3.8'

services:
  mysql:
    image: mysql:9.1
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: graphql_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuser
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
